[package]
name = "back"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
chrono-tz = "0.10.0"

regex = "1"
sqlx = "0.8.2"  features = ["runtime-tokio-rustls", "postgres"]
tokio = "1.41.0"
